### ISSUE TITLE
Webhook server over TLS/HTTPS

### ISSUE THREAD

**Issue by fancywriter** [tg-rs/tgbot#23]
According to the telegram bot API [documentation](https://core.telegram.org/bots/api#setwebhook) I must use TLS (HTTPS), even though I may use self-signed certificates for that purpose.
However, I don't see a clear way how to do this... I have [this run_server function](https://github.com/tg-rs/tgbot/blob/119d99ee141ffa79d4709da12f8f4ea07897a5ba/src/webhook.rs#L161) which doesn't accept any configuration for TLS. I see it uses hyper under the hood.

Am I right that TLS is not supported? Just yet... What options do I have? Either modifying the code to support it (I am kind a new in Rust, though it's interesting challenge and I can try if find some free time) or running as it as (let's say on port 80) and running something like haproxy (other options?) translating it HTTP to HTTPS on another port, let's say 443 and I can open 443 to the world, not opening port 80?

**Comment by rossnomann** [comment]
Use nginx

**Comment by fancywriter** [comment]
Thanks!
Just for the record, it took some effort. I think it could be documented somewhere better (had to gather different pieces).

First, I had to generate self-signed certificate (alternatively one could use CAs like let's encrypt, but telegram API works nice with self-signed too) according to this page https://core.telegram.org/bots/self-signed

```
openssl req -newkey rsa:2048 -sha256 -nodes -keyout YOURPRIVATE.key -x509 -days 365 -out YOURPUBLIC.pem -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN=YOURDOMAIN.EXAMPLE"
```
What's important, the domain name **should be actual domain name**. Just any random example will not work.

And in nginx.conf (assuming telegram bot is listening on port 8080, it could be any port):
```
server {
  listen 443 ssl;
  server_name localhost;
  location /bot-api-path {
    proxy_pass http://localhost:8080;
  }
  ssl_certificate /etc/ssl/nginx/YOURPUBLIC.pem;
  ssl_certificate_key /etc/ssl/nginx/YOURPRIVATE.key;
}
```

And of course public certificate must be supplied while setting up webhook:
```
curl -F url=https://example.com/bot-api-path -F certificate=@YOURPUBLIC.pem https://api.telegram.org/bot<telegram_token>/setWebhook
```

To verify that it's set up correctly
```
curl https://api.telegram.org/bot<telegram_token>/getWebhookInfo
```
should return something similar to
```
{
  "ok": true,
  "result": {
    "url": "https://example.com/bot-api-path",
    "has_custom_certificate": true,
    "pending_update_count": 0,
    "max_connections": 40,
    "ip_address": "???"
  }
}
```
