### ISSUE TITLE
Add code coeverage support to travis.

### ISSUE THREAD

**Issue by vldm** [tg-rs/tgbot#28]
You need to check your test coverage in order to deliver reliable product!

for reference, check: 
1. https://github.com/codecov/example-rust
2. https://users.rust-lang.org/t/tutorial-how-to-collect-test-coverages-for-rust-project/650
3. https://github.com/xd009642/tarpaulin
4. https://github.com/kennytm/cargo-kcov
5. https://github.com/mozilla/grcov

**Comment by rossnomann** [comment]
Resolved in #31
