### ISSUE TITLE
Upgrade to tokio 1.0

### ISSUE THREAD

**Issue by incker** [tg-rs/tgbot#3]
New version of tokio is released
tgbot version of tokio is 0.2 [Cargo.toml](https://github.com/tg-rs/tgbot/blob/master/Cargo.toml)

Better upgrade, to avoid downloading two versions of tokio in projects

**Comment by rossnomann** [comment]
Started work on upgrading in tokio-0.3 branch. 
Let's wait for hyperium/hyper#2302 and seanmonstar/reqwest#1060

**Comment by rossnomann** [comment]
Done
