### ISSUE TITLE
Ability to post messages by external events

### ISSUE THREAD

**Issue by ademonov** [tg-rs/tgbot#39]
Current Dispatcher implementation supposes that you can react on incoming commands and/or messages only.
But what if you want to post the messages by external events. For instance by timer. Like you want to post a new message to the channel every hour.

**Comment by rossnomann** [comment]
I think this should be implemented in framework, not core library

**Comment by rossnomann** [comment]
After discussion we decided to close this issue because it is responsibility of the user of the library.
Dispatcher should be aware of Telegram updates only and you can easily use Api wherever you want.
Example for timer:
```
use tokio_timer::Interval;
use tokio;
use std::time::{Instant, Duration};
use futures::{Stream, Future};

fn main() {
    let interval = Interval::new(Instant::now(), Duration::from_secs(3600));
    tokio::run(interval.for_each(|_| {
        println!("SEND MESSAGE HERE");
        Ok(())
    }).then(|_| Ok(())));
}```
